apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc-updated1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

