apiVersion: v1
kind: Service
metadata:
  name: jenkins-service-clusterip1
spec:
  selector:
    app: jenkins1
  ports:
    - name: http-port
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: jnlp-port
      protocol: TCP
      port: 50000
      targetPort: 50000

